import type { SidebarsConfig } from '@docusaurus/plugin-content-docs';
import apiSidebar from './docs/api-reference/sidebar';

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */
const sidebars: SidebarsConfig = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  //tutorialSidebar: [{ type: 'autogenerated', dirName: '.' }],

  // But you can create a sidebar manually
  /*
  tutorialSidebar: [
    'intro',
    'hello',
    {
      type: 'category',
      label: 'Tutorial',
      items: ['tutorial-basics/create-a-document'],
    },
  ],
   */
  backendQuarkusSidebar: [
    {
      type: 'doc',
      id: 'backend-java-quarkus/intro',
      label: 'Introducción',
    },
    {
      type: 'category',
      label: 'Tema 1 - Fundamentos',
      collapsed: false,
      items: [
        'backend-java-quarkus/fundamentos/java',
        'backend-java-quarkus/fundamentos/quarkus',
        'backend-java-quarkus/fundamentos/gradle',
        'backend-java-quarkus/fundamentos/graalvm',
        'backend-java-quarkus/fundamentos/arquitectura-hexagonal',
        'backend-java-quarkus/fundamentos/especificacion-tecnica',
      ],
    },
    {
      type: 'category',
      label: 'Tema 2 - APIs, Autenticación y Seguridad',
      collapsed: true,
      items: [
        {
          type: 'category',
          label: 'OpenAPI y Swagger',
          link: {
            type: 'doc',
            id: 'backend-java-quarkus/seguridad/introduccion-openapi',
          },
          items: (apiSidebar as any[])
            .filter((item) => item.type === 'category')
            .flatMap((category) => category.items),
        },
        {
          type: 'category',
          label: 'Keycloak: Identity and Access Management',
          link: {
            type: 'doc',
            id: 'backend-java-quarkus/seguridad/introduccion-keycloak',
          },
          items: [
            'backend-java-quarkus/seguridad/configuracion-keycloak',
          ],
        },
        'backend-java-quarkus/seguridad/validacion-openapi-seguridad',
      ],
    },
    {
      type: 'category',
      label: 'Tema 3 - APIs Reactivas',
      collapsed: true,
      items: [
        'backend-java-quarkus/auditoria/microservicio-auditoria',
        'backend-java-quarkus/auditoria/integracion-restclient',
      ],
    },
    {
      type: 'category',
      label: 'Tema 4 - Persistencia y Caché',
      collapsed: true,
      items: [
        'backend-java-quarkus/persistencia-cache/persistencia-cqrs-postgres',
        'backend-java-quarkus/persistencia-cache/cache-redis',
      ],
    },
    {
      type: 'category',
      label: 'Tema 5 - Resiliencia y Tolerancia a Fallos',
      collapsed: true,
      items: [
        'backend-java-quarkus/resiliencia/fault-tolerance',
        'backend-java-quarkus/resiliencia/escenarios-falla-audit',
      ],
    },
    {
      type: 'category',
      label: 'Tema 6 - Arquitectura Orientada a Eventos y MFA',
      collapsed: true,
      items: [
        'backend-java-quarkus/event-driven-mfa/event-bus-mfa',
      ],
    },

  ],
};

export default sidebars;
